# -*- coding: utf-8 -*-
"""
Low WBC (white blood cells) blog article — full body content for all 9 languages.
Used by blog_i18n._article_low_wbc(). Sections: intro, what-is-wbc, what-low-means,
common-causes, temporary, drugs-infections-immune, result-alone, other-params,
when-to-see-doctor, how-norya-helps, cta, disclaimer.
"""
from __future__ import annotations

LANGS = ("tr", "en", "es", "de", "fr", "it", "he", "hi", "ar")


def _sections_en() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Low WBC: common causes explained",
                body_html="<p>A low white blood cell count (WBC) on your lab report can feel worrying, but it does not always mean something serious. Understanding what WBC measures and what commonly causes a low result can help you prepare for a calm conversation with your doctor. This guide explains low WBC in plain language—without causing alarm—and points you to the right next steps.</p>"),
        Section(id="what-is-wbc", level=2, heading="What is WBC and what does it measure?",
                body_html="<p><strong>WBC</strong> (white blood cells, or leukocytes) is the total number of white blood cells in a given volume of blood. These cells help your body fight infections and respond to inflammation. A routine <a href=\"/en/blog/how-to-understand-wbc-rbc-hgb-and-hct\">complete blood count (CBC)</a> includes WBC; the lab may also report a &ldquo;differential&rdquo; (neutrophils, lymphocytes, monocytes, etc.). <strong>Low WBC</strong> (leukopenia) means the total count is below the lab&rsquo;s reference range—but the total is not the same as &ldquo;low neutrophils&rdquo; alone: the differential shows which type is low and helps your doctor interpret the result.</p>"),
        Section(id="what-low-means", level=2, heading="What does low WBC mean?",
                body_html="<p>A low WBC means your blood has fewer white blood cells than the reference range for that lab. It can be due to the bone marrow making fewer cells, cells being used or destroyed faster, or a mix of both. It is a <em>finding</em>, not a diagnosis: many causes are temporary or harmless in context, while others need follow-up. Your doctor will look at the WBC differential (e.g. low neutrophils vs low lymphocytes), your symptoms, and other results to decide what it means for you.</p>"),
        Section(id="common-causes", level=2, heading="Common causes of low WBC",
                body_html="<p>Typical causes include: <strong>certain medications</strong> (e.g. some chemotherapy, immunosuppressants, or drugs that can affect the bone marrow); <strong>viral infections</strong> (e.g. flu, COVID-19, or other viruses that temporarily lower counts); <strong>bone marrow suppression</strong> from illness or treatment; <strong>nutritional deficiencies</strong> (e.g. B12 or folate) that affect blood cell production; <strong>autoimmune or inflammatory conditions</strong>; and sometimes <strong>spleen-related</strong> or other factors. Not everyone with a low WBC has a serious condition—context matters.</p>"),
        Section(id="temporary", level=2, heading="When can low WBC be temporary?",
                body_html="<p>WBC can dip temporarily after a viral infection, during or shortly after some treatments, or with stress on the bone marrow. In such cases, a repeat test after a few weeks often shows the count back within range. Your doctor will tell you whether a repeat is needed and when. Avoid assuming the worst from a single low result.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="Medications, infections, immune system, and nutrition",
                body_html="<p><strong>Medications:</strong> Some drugs can lower WBC; your doctor will review your list and may adjust or monitor. <strong>Infections:</strong> Viral infections often cause a temporary drop in white cells (or in one type, e.g. neutrophils); bacterial or other infections can too, depending on timing. <strong>Immune or inflammatory conditions</strong> can affect production or survival of white cells. <strong>Nutrition:</strong> Severe deficiency in B12, folate, or copper can affect blood cell production. None of this means your immune system is &ldquo;weak&rdquo; in a simple sense—your doctor will interpret in context. If you want a clearer view of your full report, you can <a href=\"/analyze\">upload it to Norya</a> for a plain-language summary before your visit.</p>"),
        Section(id="result-alone", level=2, heading="Is the result enough on its own?",
                body_html="<p>No. A single low WBC does not tell you the cause or whether it is serious. Your doctor will combine it with the <strong>WBC differential</strong> (neutrophils, <a href=\"/en/blog/lymphocytes-high-or-low\">lymphocytes</a>, <a href=\"/en/blog/monocytes-high-meaning\">monocytes</a>, etc.), other blood counts (e.g. <a href=\"/en/blog/what-do-low-or-high-platelets-mean\">platelets</a>, red cells, haemoglobin), your symptoms, and history. Lab results are one part of the picture—clinical assessment is essential.</p>"),
        Section(id="other-params", level=2, heading="What other parameters do doctors usually look at?",
                body_html="<p>They often review the <strong>WBC differential</strong> (which cell type is low), <strong>red blood cell counts and haemoglobin</strong>, <strong>platelets</strong>, and sometimes <strong>vitamin B12</strong>, <strong>folate</strong>, or other tests depending on the situation. Repeat WBC at a later date may be suggested to see if the count recovers. The goal is to match the numbers to your health story.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="When is medical evaluation needed?",
                body_html="<p>Any persistent or unexplained low WBC should be discussed with a doctor. Seek prompt review if you have fever, repeated infections, unexplained fatigue, mouth sores, or easy bruising or bleeding—or if your report shows a very low count or other abnormal results. Even without symptoms, sharing an abnormal result with your doctor is the right step so they can interpret it and suggest follow-up if needed.</p>"),
        Section(id="how-norya-helps", level=2, heading="How Norya makes this result easier to understand",
                body_html="<p>Norya does not diagnose—we help you prepare. You can <a href=\"/analyze\">upload your lab report</a> and get a clear, structured summary that explains your values (including WBC and the differential) in plain language. That can help you understand your result better and ask focused questions at your appointment. For options and pricing, see our <a href=\"/pricing\">pricing page</a>.</p>"),
        Section(id="cta", level=2, heading="Next step",
                body_html="<p>If you want a clearer explanation of your blood test—including WBC and other CBC results—you can <a href=\"/analyze\">start an analysis</a> with Norya. Use it to prepare for your doctor visit, not as a substitute for medical advice.</p>"),
        Section(id="disclaimer", level=2, heading="Disclaimer",
                body_html="<p><strong>This content is for information only and does not replace medical advice or diagnosis.</strong> A low WBC can have many causes; only a healthcare professional who knows your history and context can interpret your result properly. Always discuss your lab results with a doctor.</p>"),
    ]


def _sections_es() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Glóbulos blancos bajos: causas frecuentes",
                body_html="<p>Un recuento bajo de glóbulos blancos (WBC) en el análisis puede inquietar, pero no siempre indica algo grave. Entender qué mide el WBC y qué suele causar un valor bajo ayuda a preparar una conversación tranquila con tu médico. Esta guía explica el WBC bajo en lenguaje claro—sin alarmar—y orienta sobre los siguientes pasos.</p>"),
        Section(id="what-is-wbc", level=2, heading="¿Qué es el WBC y qué mide?",
                body_html="<p>El <strong>WBC</strong> (glóbulos blancos o leucocitos) es el número total de glóbulos blancos en un volumen de sangre. Ayudan a combatir infecciones y a responder a la inflamación. Un <a href=\"/es/blog/como-entender-wbc-rbc-hgb-y-hct\">hemograma</a> incluye el WBC; a veces el laboratorio da la fórmula leucocitaria (neutrófilos, linfocitos, monocitos, etc.). <strong>WBC bajo</strong> (leucopenia) significa que el total está por debajo del rango de referencia—pero el total no es lo mismo que solo \"neutrófilos bajos\": la fórmula muestra qué tipo está bajo y ayuda al médico a interpretar.</p>"),
        Section(id="what-low-means", level=2, heading="¿Qué significa un WBC bajo?",
                body_html="<p>Un WBC bajo indica que hay menos glóbulos blancos de lo que marca el rango de referencia. Puede deberse a menor producción en la médula ósea, mayor uso o destrucción de células, o ambos. Es un <em>hallazgo</em>, no un diagnóstico: muchas causas son transitorias o inocuas en contexto; otras requieren seguimiento. El médico valorará la fórmula (p. ej. neutrófilos vs linfocitos bajos), tus síntomas y el resto de resultados.</p>"),
        Section(id="common-causes", level=2, heading="Causas frecuentes de WBC bajo",
                body_html="<p>Causas típicas: <strong>ciertos medicamentos</strong> (quimioterapia, inmunosupresores u otros que afectan la médula); <strong>infecciones virales</strong> (gripe, COVID-19, etc.) que bajan el recuento de forma transitoria; <strong>supresión medular</strong> por enfermedad o tratamiento; <strong>déficits nutricionales</strong> (B12, folato) que afectan la producción; <strong>enfermedades autoinmunes o inflamatorias</strong>; a veces factores <strong>esplénicos</strong> u otros. No todo WBC bajo implica gravedad—el contexto importa.</p>"),
        Section(id="temporary", level=2, heading="¿Cuándo puede ser transitorio?",
                body_html="<p>El WBC puede bajar de forma temporal tras una infección viral, durante o tras ciertos tratamientos, o por estrés sobre la médula. En esos casos, una repetición a las pocas semanas suele mostrar el valor dentro del rango. Tu médico indicará si conviene repetir y cuándo. Evita sacar conclusiones negativas de un solo resultado bajo.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="Medicamentos, infecciones, inmunidad y nutrición",
                body_html="<p><strong>Medicamentos:</strong> Algunos pueden bajar el WBC; el médico revisará tu lista y podrá ajustar o vigilar. <strong>Infecciones:</strong> Las virales suelen bajar los glóbulos blancos (o un tipo, p. ej. neutrófilos) de forma transitoria; las bacterianas u otras también pueden influir. <strong>Enfermedades inmunitarias o inflamatorias</strong> pueden afectar producción o supervivencia. <strong>Nutrición:</strong> Déficit importante de B12, folato o cobre puede afectar la producción. Nada de esto implica por sí solo un sistema inmune \"débil\"; el médico lo interpreta en contexto. Para una visión más clara de tu informe, puedes <a href=\"/analyze\">subirlo a Norya</a> y obtener un resumen en lenguaje sencillo antes de la visita.</p>"),
        Section(id="result-alone", level=2, heading="¿El resultado basta por sí solo?",
                body_html="<p>No. Un WBC bajo aislado no indica la causa ni la gravedad. El médico lo combina con la <strong>fórmula leucocitaria</strong>, otros recuentos (<a href=\"/es/blog/plaquetas-altas-o-bajas-que-significa\">plaquetas</a>, <a href=\"/es/blog/lymphocytes-high-or-low\">linfocitos</a>, <a href=\"/es/blog/monocytes-high-meaning\">monocitos</a>, hemoglobina), síntomas e historia. Los resultados son una parte del cuadro—la valoración clínica es esencial.</p>"),
        Section(id="other-params", level=2, heading="¿Qué otros parámetros suelen revisar?",
                body_html="<p>Suelen revisar la <strong>fórmula leucocitaria</strong> (qué tipo está bajo), <strong>glóbulos rojos y hemoglobina</strong>, <strong>plaquetas</strong> y a veces <strong>B12</strong>, <strong>folato</strong> u otras pruebas según el caso. Pueden pedir repetir el WBC más adelante para ver si se recupera. El objetivo es encajar los números con tu situación.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="¿Cuándo hay que hacer valoración médica?",
                body_html="<p>Cualquier WBC bajo persistente o sin explicación debe comentarse con un médico. Pide valoración pronto si tienes fiebre, infecciones repetidas, cansancio sin explicación, llagas en boca o moretones/sangrado fácil—o si el informe muestra un valor muy bajo u otras alteraciones. Aun sin síntomas, compartir un resultado anormal con tu médico es lo correcto para que lo interprete y proponga seguimiento si hace falta.</p>"),
        Section(id="how-norya-helps", level=2, heading="Cómo Norya hace más comprensible este resultado",
                body_html="<p>Norya no diagnostica—te ayuda a prepararte. Puedes <a href=\"/analyze\">subir tu informe</a> y obtener un resumen claro que explica tus valores (WBC y fórmula) en lenguaje sencillo. Así entenderás mejor el resultado y podrás hacer preguntas concretas en la consulta. Para opciones y precios: <a href=\"/pricing\">precios</a>.</p>"),
        Section(id="cta", level=2, heading="Siguiente paso",
                body_html="<p>Si quieres una explicación más clara de tu análisis—WBC y resto del hemograma—puedes <a href=\"/analyze\">iniciar un análisis</a> con Norya. Úsalo para preparar la consulta, no como sustituto del criterio médico.</p>"),
        Section(id="disclaimer", level=2, heading="Aviso",
                body_html="<p><strong>Este contenido es solo informativo y no sustituye consejo ni diagnóstico médico.</strong> Un WBC bajo puede deberse a muchas causas; solo un profesional que conozca tu historia puede interpretarlo. Comenta siempre tus resultados con un médico.</p>"),
    ]


def _sections_de() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Leukozyten zu niedrig: häufige Ursachen",
                body_html="<p>Ein niedriger Leukozytenwert (WBC) im Laborbericht kann beunruhigen—er bedeutet aber nicht immer etwas Schwerwiegendes. Zu verstehen, was der WBC misst und was häufig einen niedrigen Wert verursacht, hilft Ihnen, ruhig mit dem Arzt zu sprechen. Dieser Ratgeber erklärt niedrige Leukozyten in verständlicher Sprache—ohne Alarm—und weist auf die richtigen nächsten Schritte hin.</p>"),
        Section(id="what-is-wbc", level=2, heading="Was ist der WBC und was wird gemessen?",
                body_html="<p>Der <strong>WBC</strong> (weiße Blutkörperchen, Leukozyten) ist die Gesamtzahl der weißen Blutkörperchen in einem bestimmten Blutvolumen. Sie helfen bei der Abwehr von Infektionen und bei Entzündungsreaktionen. Ein <a href=\"/de/blog/wbc-rbc-und-hct-verstehen\">Blutbild</a> enthält den WBC; manchmal liefert das Labor ein Differentialblutbild (Neutrophile, Lymphozyten, Monozyten usw.). <strong>Niedriger WBC</strong> (Leukopenie) bedeutet, dass der Wert unter dem Referenzbereich liegt—der Gesamtwert ist aber nicht dasselbe wie nur \"niedrige Neutrophile\": das Differential zeigt, welche Zellart niedrig ist und hilft dem Arzt bei der Einordnung.</p>"),
        Section(id="what-low-means", level=2, heading="Was bedeutet ein niedriger WBC?",
                body_html="<p>Ein niedriger WBC bedeutet, dass weniger weiße Blutkörperchen als im Referenzbereich vorhanden sind. Ursachen können geringere Bildung im Knochenmark, stärkerer Verbrauch oder Abbau der Zellen oder beides sein. Es ist ein <em>Befund</em>, keine Diagnose: Viele Ursachen sind vorübergehend oder im Kontext unkritisch; andere erfordern Abklärung. Der Arzt wertet das Differential (z. B. Neutrophile vs. Lymphozyten), Ihre Symptome und weitere Ergebnisse aus.</p>"),
        Section(id="common-causes", level=2, heading="Häufige Ursachen für niedrigen WBC",
                body_html="<p>Typische Ursachen: <strong>bestimmte Medikamente</strong> (z. B. manche Chemotherapie, Immunsuppressiva oder andere, die das Knochenmark beeinflussen); <strong>virale Infektionen</strong> (z. B. Grippe, COVID-19), die den Wert vorübergehend senken können; <strong>Knochenmarksuppression</strong> durch Krankheit oder Behandlung; <strong>Mangelernährung</strong> (B12, Folsäure), die die Blutbildung beeinträchtigt; <strong>autoimmune oder entzündliche Erkrankungen</strong>; teils <strong>milzbedingte</strong> oder andere Faktoren. Nicht bei jedem niedrigen WBC liegt eine schwere Erkrankung vor—der Kontext zählt.</p>"),
        Section(id="temporary", level=2, heading="Wann kann der WBC vorübergehend niedrig sein?",
                body_html="<p>Der WBC kann nach einer viralen Infektion, unter oder nach bestimmten Behandlungen oder bei Belastung des Knochenmarks vorübergehend sinken. In solchen Fällen zeigt eine Kontrolle nach einigen Wochen oft wieder einen Wert im Referenzbereich. Der Arzt sagt Ihnen, ob und wann eine Wiederholung sinnvoll ist. Schließen Sie nicht vorschnell das Schlimmste aus einem einzelnen niedrigen Wert.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="Medikamente, Infektionen, Immunsystem und Ernährung",
                body_html="<p><strong>Medikamente:</strong> Einige können den WBC senken; der Arzt prüft Ihre Medikamentenliste und kann anpassen oder überwachen. <strong>Infektionen:</strong> Virale Infektionen senken oft vorübergehend die weißen Zellen (oder eine Unterart, z. B. Neutrophile); bakterielle oder andere Infektionen können je nach Zeitpunkt ebenfalls Einfluss haben. <strong>Immun- oder Entzündungserkrankungen</strong> können Bildung oder Überleben der Zellen beeinflussen. <strong>Ernährung:</strong> Starker Mangel an B12, Folsäure oder Kupfer kann die Blutbildung beeinträchtigen. Das bedeutet nicht pauschal ein \"schwaches\" Immunsystem—der Arzt ordnet es im Kontext ein. Für eine klarere Übersicht Ihres Befunds können Sie ihn vor dem Termin bei <a href=\"/analyze\">Norya hochladen</a> und eine verständliche Auswertung erhalten.</p>"),
        Section(id="result-alone", level=2, heading="Reicht der Befund allein?",
                body_html="<p>Nein. Ein einzelner niedriger WBC nennt weder die Ursache noch die Schwere. Der Arzt wertet ihn zusammen mit dem <strong>Differentialblutbild</strong> (<a href=\"/de/blog/lymphocytes-high-or-low\">Lymphozyten</a>, <a href=\"/de/blog/monocytes-high-meaning\">Monozyten</a> usw.), anderen Werten (<a href=\"/de/blog/thrombozyten-zu-hoch-oder-zu-niedrig\">Thrombozyten</a>, Erythrozyten, Hämoglobin), Ihren Symptomen und der Anamnese aus. Laborwerte sind ein Baustein—die klinische Beurteilung ist entscheidend.</p>"),
        Section(id="other-params", level=2, heading="Welche weiteren Parameter prüft der Arzt?",
                body_html="<p>Oft werden das <strong>Differentialblutbild</strong> (welche Zellart niedrig ist), <strong>Erythrozyten und Hämoglobin</strong>, <strong>Thrombozyten</strong> und ggf. <strong>B12</strong>, <strong>Folsäure</strong> oder andere Tests je nach Situation beurteilt. Eine WBC-Kontrolle zu einem späteren Zeitpunkt kann angeordnet werden, um zu sehen, ob sich der Wert erholt. Ziel ist, die Werte mit Ihrer Situation in Einklang zu bringen.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="Wann ist eine ärztliche Abklärung nötig?",
                body_html="<p>Jeder anhaltende oder unklare niedrige WBC sollte mit einem Arzt besprochen werden. Lassen Sie zeitnah abklären bei Fieber, wiederholten Infektionen, unerklärlicher Müdigkeit, Mundschleimhautveränderungen oder Neigung zu Blutungen bzw. Blutergüssen—oder wenn der Bericht einen sehr niedrigen Wert oder weitere Auffälligkeiten zeigt. Auch ohne Beschwerden ist es richtig, einen auffälligen Befund mit dem Arzt zu besprechen und ggf. Nachkontrollen durchführen zu lassen.</p>"),
        Section(id="how-norya-helps", level=2, heading="Wie Norya diesen Befund verständlicher macht",
                body_html="<p>Norya stellt keine Diagnosen—wir helfen bei der Vorbereitung. Sie können Ihren <a href=\"/analyze\">Laborbericht hochladen</a> und eine klare Auswertung erhalten, die Ihre Werte (inkl. WBC und Differential) verständlich erklärt. So verstehen Sie Ihren Befund besser und können gezielte Fragen stellen. Optionen und Preise: <a href=\"/pricing\">Preise</a>.</p>"),
        Section(id="cta", level=2, heading="Nächster Schritt",
                body_html="<p>Wenn Sie Ihren Blutbefund—WBC und restliches Blutbild—klarer einordnen möchten, können Sie bei Norya <a href=\"/analyze\">eine Analyse starten</a>. Nutzen Sie sie zur Vorbereitung auf den Arzttermin, nicht als Ersatz für medizinische Beratung.</p>"),
        Section(id="disclaimer", level=2, heading="Hinweis",
                body_html="<p><strong>Dieser Inhalt dient nur der Information und ersetzt keine medizinische Beratung oder Diagnose.</strong> Ein niedriger WBC kann viele Ursachen haben; nur eine Fachperson mit Kenntnis Ihrer Anamnese kann ihn einordnen. Besprechen Sie Laborergebnisse immer mit einem Arzt.</p>"),
    ]


def _sections_fr() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Globules blancs bas : causes fréquentes",
                body_html="<p>Un taux bas de globules blancs (GB) sur votre bilan peut inquiéter, mais il ne signifie pas toujours quelque chose de grave. Comprendre ce que mesure le taux de GB et ce qui fait souvent baisser le résultat aide à préparer un dialogue serein avec votre médecin. Ce guide explique le taux bas de GB en langage clair—sans alarme—et oriente vers les bons prochaines étapes.</p>"),
        Section(id="what-is-wbc", level=2, heading="Qu'est-ce que le taux de GB et que mesure-t-on ?",
                body_html="<p>Le <strong>taux de GB</strong> (globules blancs ou leucocytes) est le nombre total de globules blancs dans un volume de sang donné. Ils aident à lutter contre les infections et à réagir à l'inflammation. Une <a href=\"/fr/blog/comprendre-globules-blancs-rouges-hgb-hct\">numération formule sanguine (NFS)</a> inclut les GB ; le laboratoire peut aussi donner la formule (neutrophiles, lymphocytes, monocytes, etc.). Un <strong>taux bas de GB</strong> (leucopénie) signifie que le total est en dessous de l'intervalle de référence—mais le total n'est pas la même chose que « neutrophiles bas » seuls : la formule montre quel type est bas et aide le médecin à interpréter.</p>"),
        Section(id="what-low-means", level=2, heading="Que signifie un taux bas de GB ?",
                body_html="<p>Un taux bas signifie qu'il y a moins de globules blancs que l'intervalle de référence. Les causes peuvent être une production moindre par la moelle osseuse, une consommation ou destruction plus rapide des cellules, ou les deux. C'est un <em>constat</em>, pas un diagnostic : beaucoup de causes sont transitoires ou bénignes dans le contexte ; d'autres nécessitent un suivi. Le médecin s'appuie sur la formule (p. ex. neutrophiles vs lymphocytes bas), vos symptômes et le reste du bilan.</p>"),
        Section(id="common-causes", level=2, heading="Causes fréquentes de GB bas",
                body_html="<p>Causes typiques : <strong>certains médicaments</strong> (chimiothérapie, immunosuppresseurs ou autres affectant la moelle) ; <strong>infections virales</strong> (grippe, COVID-19, etc.) qui font baisser le taux temporairement ; <strong>suppression médullaire</strong> par la maladie ou le traitement ; <strong>carences nutritionnelles</strong> (B12, folates) ; <strong>maladies auto-immunes ou inflammatoires</strong> ; parfois facteurs <strong>spléniques</strong> ou autres. Un taux bas de GB n'est pas toujours grave—le contexte compte.</p>"),
        Section(id="temporary", level=2, heading="Quand le taux bas peut-il être transitoire ?",
                body_html="<p>Le taux peut baisser temporairement après une infection virale, pendant ou après certains traitements, ou en cas de stress sur la moelle. Dans ces cas, un contrôle quelques semaines plus tard montre souvent un retour à la normale. Le médecin vous dira s'il faut répéter et quand. Évitez de conclure au pire à partir d'un seul résultat bas.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="Médicaments, infections, immunité et nutrition",
                body_html="<p><strong>Médicaments :</strong> Certains peuvent faire baisser les GB ; le médecin revoit votre liste et peut adapter ou surveiller. <strong>Infections :</strong> Les virales font souvent baisser les globules blancs (ou un type, p. ex. neutrophiles) temporairement ; les bactériennes ou autres peuvent aussi jouer. <strong>Maladies immunitaires ou inflammatoires</strong> peuvent affecter la production ou la survie des cellules. <strong>Nutrition :</strong> Une carence importante en B12, folates ou cuivre peut affecter la production. Rien de tout cela ne signifie à lui seul un système immunitaire « faible »—le médecin interprète dans le contexte. Pour une vision plus claire de votre bilan, vous pouvez <a href=\"/analyze\">l'envoyer à Norya</a> pour un résumé en langage simple avant la consultation.</p>"),
        Section(id="result-alone", level=2, heading="Le résultat suffit-il à lui seul ?",
                body_html="<p>Non. Un taux bas isolé ne donne ni la cause ni la gravité. Le médecin le combine à la <strong>formule sanguine</strong>, aux autres chiffres (<a href=\"/fr/blog/plaquettes-trop-hautes-ou-basses\">plaquettes</a>, <a href=\"/fr/blog/lymphocytes-high-or-low\">lymphocytes</a>, <a href=\"/fr/blog/monocytes-high-meaning\">monocytes</a>, hémoglobine), à vos symptômes et à l'anamnèse. Les résultats ne sont qu'une pièce du puzzle—l'évaluation clinique est essentielle.</p>"),
        Section(id="other-params", level=2, heading="Quels autres paramètres le médecin regarde-t-il ?",
                body_html="<p>Il regarde souvent la <strong>formule</strong> (quel type est bas), les <strong>globules rouges et l'hémoglobine</strong>, les <strong>plaquettes</strong>, et parfois la <strong>B12</strong>, les <strong>folates</strong> ou d'autres examens selon le cas. Une répétition du taux de GB plus tard peut être proposée pour voir s'il se normalise. L'objectif est de faire correspondre les chiffres à votre situation.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="Quand faut-il une évaluation médicale ?",
                body_html="<p>Tout taux bas persistant ou inexpliqué doit être discuté avec un médecin. Consultez sans tarder en cas de fièvre, d'infections à répétition, de fatigue inexpliquée, de lésions buccales ou de bleus/saignements faciles—ou si le compte rendu indique un taux très bas ou d'autres anomalies. Même sans symptômes, montrer un résultat anormal à votre médecin est la bonne démarche pour qu'il l'interprète et propose un suivi si besoin.</p>"),
        Section(id="how-norya-helps", level=2, heading="Comment Norya rend ce résultat plus lisible",
                body_html="<p>Norya ne pose pas de diagnostic—nous vous aident à vous préparer. Vous pouvez <a href=\"/analyze\">envoyer votre bilan</a> et obtenir un résumé clair qui explique vos valeurs (GB et formule) en langage simple. Ainsi vous comprenez mieux votre résultat et pouvez poser les bonnes questions en consultation. Options et tarifs : <a href=\"/pricing\">tarifs</a>.</p>"),
        Section(id="cta", level=2, heading="Prochaine étape",
                body_html="<p>Pour une explication plus claire de votre bilan—GB et reste de la NFS—vous pouvez <a href=\"/analyze\">lancer une analyse</a> avec Norya. À utiliser pour préparer la consultation, pas en remplacement d'un avis médical.</p>"),
        Section(id="disclaimer", level=2, heading="Avertissement",
                body_html="<p><strong>Ce contenu est à titre informatif uniquement et ne remplace pas un avis ou un diagnostic médical.</strong> Un taux bas de GB peut avoir de nombreuses causes ; seul un professionnel qui connaît votre contexte peut l'interpréter. Discutez toujours de vos résultats avec un médecin.</p>"),
    ]


def _sections_it() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Globuli bianchi bassi: cause comuni",
                body_html="<p>Un valore basso di globuli bianchi (WBC) sul referto può preoccupare, ma non indica sempre qualcosa di grave. Capire cosa misura il WBC e cosa causa spesso un valore basso aiuta a preparare un colloquio sereno con il medico. Questa guida spiega il WBC basso in linguaggio chiaro—senza allarmismi—e orienta sui passi successivi.</p>"),
        Section(id="what-is-wbc", level=2, heading="Cos'è il WBC e cosa si misura?",
                body_html="<p>Il <strong>WBC</strong> (globuli bianchi o leucociti) è il numero totale di globuli bianchi in un dato volume di sangue. Aiutano a combattere le infezioni e a rispondere all'infiammazione. Un <a href=\"/it/blog/come-leggere-wbc-rbc-hgb-hct\">emocromo</a> include il WBC; a volte il laboratorio fornisce la formula leucocitaria (neutrofili, linfociti, monociti, ecc.). <strong>WBC basso</strong> (leucopenia) significa che il totale è sotto l'intervallo di riferimento—ma il totale non è la stessa cosa di solo \"neutrofili bassi\": la formula mostra quale tipo è basso e aiuta il medico a interpretare.</p>"),
        Section(id="what-low-means", level=2, heading="Cosa significa un WBC basso?",
                body_html="<p>Un WBC basso indica che ci sono meno globuli bianchi dell'intervallo di riferimento. Può dipendere da minore produzione midollare, maggiore consumo o distruzione delle cellule, o entrambi. È un <em>reperto</em>, non una diagnosi: molte cause sono transitorie o innocue nel contesto; altre richiedono follow-up. Il medico valuta la formula (es. neutrofili vs linfociti bassi), i sintomi e il resto degli esami.</p>"),
        Section(id="common-causes", level=2, heading="Cause comuni di WBC basso",
                body_html="<p>Cause tipiche: <strong>alcuni farmaci</strong> (chemioterapia, immunosoppressori o altri che influenzano il midollo); <strong>infezioni virali</strong> (influenza, COVID-19, ecc.) che abbassano il valore temporaneamente; <strong>soppressione midollare</strong> da malattia o terapia; <strong>carenze nutrizionali</strong> (B12, folati); <strong>malattie autoimmuni o infiammatorie</strong>; a volte fattori <strong>splenici</strong> o altri. Non tutti i WBC bassi sono gravi—il contesto conta.</p>"),
        Section(id="temporary", level=2, heading="Quando il WBC basso può essere transitorio?",
                body_html="<p>Il valore può scendere temporaneamente dopo un'infezione virale, durante o dopo certi trattamenti, o per stress sul midollo. In questi casi un controllo dopo alcune settimane spesso mostra il ritorno in range. Il medico dirà se ripetere e quando. Evitare di pensare subito al peggio per un solo valore basso.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="Farmaci, infezioni, sistema immunitario e nutrizione",
                body_html="<p><strong>Farmaci:</strong> Alcuni possono abbassare il WBC; il medico rivede la lista e può modificare o monitorare. <strong>Infezioni:</strong> Quelle virali spesso abbassano i globuli bianchi (o un tipo, es. neutrofili) temporaneamente; batteriche o altre possono influire. <strong>Malattie immunitarie o infiammatorie</strong> possono alterare produzione o sopravvivenza. <strong>Nutrizione:</strong> Carenza importante di B12, folati o rame può influire sulla produzione. Niente di ciò implica da solo un sistema immunitario \"debole\"—il medico inquadra nel contesto. Per una visione più chiara del referto puoi <a href=\"/analyze\">caricarlo su Norya</a> per un riepilogo in linguaggio semplice prima della visita.</p>"),
        Section(id="result-alone", level=2, heading="Il risultato da solo basta?",
                body_html="<p>No. Un singolo WBC basso non indica causa né gravità. Il medico lo combina con la <strong>formula leucocitaria</strong> (<a href=\"/it/blog/lymphocytes-high-or-low\">linfociti</a>, <a href=\"/it/blog/monocytes-high-meaning\">monociti</a>, ecc.), altri valori (<a href=\"/it/blog/piastrine-alte-o-basse-cosa-significa\">piastrine</a>, globuli rossi, emoglobina), sintomi e anamnesi. I risultati sono un tassello—la valutazione clinica è essenziale.</p>"),
        Section(id="other-params", level=2, heading="Quali altri parametri controlla il medico?",
                body_html="<p>Spesso controlla la <strong>formula leucocitaria</strong> (quale tipo è basso), <strong>globuli rossi ed emoglobina</strong>, <strong>piastrine</strong> e a volte <strong>B12</strong>, <strong>folati</strong> o altri esami a seconda del caso. Può richiedere la ripetizione del WBC a distanza per vedere se si normalizza. L'obiettivo è far combaciare i valori con la tua situazione.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="Quando serve una valutazione medica?",
                body_html="<p>Ogni WBC basso persistente o non spiegato va discusso con un medico. Richiedi una valutazione tempestiva in caso di febbre, infezioni ripetute, stanchezza inspiegabile, lesioni in bocca o tendenza a lividi/sanguinamenti—o se il referto indica un valore molto basso o altre alterazioni. Anche senza sintomi, mostrare un risultato alterato al medico è corretto per interpretarlo e proporre eventuale follow-up.</p>"),
        Section(id="how-norya-helps", level=2, heading="Come Norya rende più comprensibile questo risultato",
                body_html="<p>Norya non fa diagnosi—ti aiuta a prepararti. Puoi <a href=\"/analyze\">caricare il referto</a> e ottenere un riepilogo chiaro che spiega i tuoi valori (WBC e formula) in linguaggio semplice. Così capisci meglio il risultato e puoi fare domande mirate in visita. Per opzioni e prezzi: <a href=\"/pricing\">prezzi</a>.</p>"),
        Section(id="cta", level=2, heading="Prossimo passo",
                body_html="<p>Se vuoi una spiegazione più chiara del tuo esame del sangue—WBC e resto dell'emocromo—puoi <a href=\"/analyze\">avviare un'analisi</a> con Norya. Usala per prepararti alla visita, non come sostituto del parere medico.</p>"),
        Section(id="disclaimer", level=2, heading="Disclaimer",
                body_html="<p><strong>Questo contenuto è solo a scopo informativo e non sostituisce consulenza o diagnosi medica.</strong> Un WBC basso può avere molte cause; solo un professionista che conosce la tua storia può interpretarlo. Discuti sempre i risultati con un medico.</p>"),
    ]


def _sections_he() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="ספירת דם לבנים נמוכה: סיבות נפוצות",
                body_html="<p>ספירת דם לבנים (WBC) נמוכה בדו\"ח המעבדה עלולה להדאיג, אך אינה מעידה תמיד על משהו חמור. ההבנה מה WBC מודד ומה גורם לעיתים לערך נמוך עוזרת להכין שיחה רגועה עם הרופא. מדריך זה מסביר WBC נמוך בשפה פשוטה—בלי להלחיץ—ומכוון לשלבים הבאים הנכונים.</p>"),
        Section(id="what-is-wbc", level=2, heading="מהו WBC ומה נמדד?",
                body_html="<p><strong>WBC</strong> (תאי דם לבנים, לויקוציטים) הוא המספר הכולל של תאי דם לבנים בנפח דם נתון. הם עוזרים להילחם בזיהומים ולהגיב לדלקת. ב<a href=\"/he/blog/how-to-understand-wbc-rbc-hgb-and-hct\">ספירת דם מלאה</a> נכלל WBC; לעיתים המעבדה נותנת גם נוסחת דם (נויטרופילים, לימפוציטים, מונוציטים וכו'). <strong>WBC נמוך</strong> (לויקופניה) משמע שהספירה הכוללת מתחת לטווח הייחוס—אבל הספירה הכוללת אינה זהה ל\"נויטרופילים נמוכים\" בלבד: הנוסחה מראה איזה סוג נמוך ומסייעת לרופא לפרש.</p>"),
        Section(id="what-low-means", level=2, heading="מה המשמעות של WBC נמוך?",
                body_html="<p>WBC נמוך משמע פחות תאי דם לבנים מטווח הייחוס. הסיבות יכולות להיות ייצור מופחת במח העצם, שימוש או הרס מוגבר של תאים, או שילוב. זה <em>ממצא</em>, לא אבחנה: סיבות רבות זמניות או לא משמעותיות בהקשר; אחרות דורשות מעקב. הרופא יבדוק את הנוסחה (למשל נויטרופילים מול לימפוציטים נמוכים), התסמינים ושאר התוצאות.</p>"),
        Section(id="common-causes", level=2, heading="סיבות נפוצות ל-WBC נמוך",
                body_html="<p>סיבות טיפוסיות: <strong>תרופות מסוימות</strong> (כימותרפיה, אימונוסופרסיה או אחרות המשפיעות על מח העצם); <strong>זיהומים נגיפיים</strong> (שפעת, COVID-19 וכו') המורידים את הספירה זמנית; <strong>דיכוי מח עצם</strong> ממחלה או טיפול; <strong>חוסרים תזונתיים</strong> (B12, חומצה פולית); <strong>מחלות אוטואימוניות או דלקתיות</strong>; לעיתים גורמים <strong>טחוליים</strong> או אחרים. לא לכל WBC נמוך יש משמעות חמורה—ההקשר חשוב.</p>"),
        Section(id="temporary", level=2, heading="מתי WBC נמוך יכול להיות זמני?",
                body_html="<p>הערך יכול לרדת זמנית אחרי זיהום נגיפי, במהלך או אחרי טיפולים מסוימים, או במתח על מח העצם. במקרים כאלה בדיקה חוזרת אחרי כמה שבועות מראה לא פעם חזרה לטווח. הרופא יאמר אם יש צורך בחזרה ומתי. מומלץ לא להסיק את הגרוע מחד ערך נמוך בודד.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="תרופות, זיהומים, מערכת חיסון ותזונה",
                body_html="<p><strong>תרופות:</strong> חלקן עלולות להוריד WBC; הרופא יבדוק את רשימת התרופות ויתכן שיתאם או ינטר. <strong>זיהומים:</strong> נגיפיים מורידים לא פעם את התאים הלבנים (או סוג אחד, למשל נויטרופילים) זמנית; חיידקיים או אחרים יכולים גם להשפיע. <strong>מחלות חיסון או דלקת</strong> עלולות להשפיע על ייצור או הישרדות התאים. <strong>תזונה:</strong> חוסר משמעותי ב-B12, חומצה פולית או נחושת עלול להשפיע על ייצור התאים. כל זה לא מעיד בהכרח על מערכת חיסון \"חלשה\"—הרופא יפרש בהקשר. לצורך הבנה ברורה יותר של הדו\"ח אפשר <a href=\"/analyze\">להעלות אותו ל-Norya</a> ולקבל סיכום בשפה פשוטה לפני הפגישה.</p>"),
        Section(id="result-alone", level=2, heading="האם התוצאה מספיקה לבדה?",
                body_html="<p>לא. WBC נמוך בודד לא מציין סיבה או חומרה. הרופא ישלב אותו עם <strong>נוסחת הדם</strong> (<a href=\"/he/blog/lymphocytes-high-or-low\">לימפוציטים</a>, <a href=\"/he/blog/monocytes-high-meaning\">מונוציטים</a> וכו'), ספירות אחרות (<a href=\"/he/blog/what-do-low-or-high-platelets-mean\">טסיות</a>, כדוריות אדומות, המוגלובין), התסמינים נמנזה. תוצאות המעבדה הן חלק מהתמונה—ההערכה הקלינית חיונית.</p>"),
        Section(id="other-params", level=2, heading="אילו פרמטרים נוספים בודק הרופא?",
                body_html="<p>לעיתים בודקים את <strong>נוסחת הדם</strong> (איזה סוג נמוך), <strong>כדוריות אדומות והמוגלובין</strong>, <strong>טסיות</strong> ולעיתים <strong>B12</strong>, <strong>חומצה פולית</strong> או בדיקות אחרות לפי המצב. ייתכן שיומלץ לחזור על ה-WBC אחרי זמן כדי לראות אם הערך חוזר. המטרה היא להתאים את המספרים למצבך.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="מתי נדרשת הערכה רפואית?",
                body_html="<p>כל WBC נמוך מתמשך או לא מוסבר יש לדון עם רופא. פנה בהקדם להערכה אם יש חום, זיהומים חוזרים, עייפות בלתי מוסברת, פצעים בפה או נטייה לדמם/חבורות—או אם הדו\"ח מציג ערך נמוך מאוד או חריגות אחרות. גם בלי תסמינים, חשוב לחלוק תוצאה חריגה עם הרופא כדי שיוכל לפרש ולהציע מעקב אם צריך.</p>"),
        Section(id="how-norya-helps", level=2, heading="איך Norya הופכת את התוצאה הזו למובנת יותר",
                body_html="<p>ב-Norya לא מאבחנים—עוזרים לך להתכונן. אפשר <a href=\"/analyze\">להעלות את דו\"ח המעבדה</a> ולקבל סיכום ברור שמסביר את הערכים (כולל WBC והנוסחה) בשפה פשוטה. כך תבין את התוצאה טוב יותר ותוכל לשאול שאלות ממוקדות. לאפשרויות ומחירים: <a href=\"/pricing\">מחירים</a>.</p>"),
        Section(id="cta", level=2, heading="הצעד הבא",
                body_html="<p>אם תרצה הסבר ברור יותר לבדיקת הדם שלך—כולל WBC ושאר הספירה—אפשר <a href=\"/analyze\">להתחיל ניתוח</a> עם Norya. השתמש בזה כדי להתכונן לפגישה, לא כתחליף לייעוץ רפואי.</p>"),
        Section(id="disclaimer", level=2, heading="הודעה",
                body_html="<p><strong>התוכן כאן למידע בלבד ואינו מחליף ייעוץ או אבחנה רפואית.</strong> WBC נמוך יכול לנבוע מסיבות רבות; רק איש מקצוע שמכיר את ההקשר שלך יכול לפרש. תמיד יש לדון בתוצאות המעבדה עם רופא.</p>"),
    ]


def _sections_hi() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="लो WBC: आम कारणों की व्याख्या",
                body_html="<p>रिपोर्ट में वाइट ब्लड सेल काउंट (WBC) लो आने पर चिंता हो सकती है, लेकिन इसका मतलब हमेशा कुछ गंभीर नहीं होता। WBC क्या मापता है और लो रिज़ल्ट के आम कारण क्या हैं—यह समझने से डॉक्टर के साथ शांत बातचीत में मदद मिलती है। यह गाइड लो WBC को साफ भाषा में समझाती है—बिना डराए—और सही अगले कदम बताती है।</p>"),
        Section(id="what-is-wbc", level=2, heading="WBC क्या है और क्या मापा जाता है?",
                body_html="<p><strong>WBC</strong> (वाइट ब्लड सेल, ल्यूकोसाइट्स) खून की एक निश्चित मात्रा में वाइट ब्लड सेल की कुल संख्या होती है। ये इन्फेक्शन से लड़ने और सूजन पर रिस्पॉन्स करने में मदद करते हैं। रूटीन <a href=\"/hi/blog/how-to-understand-wbc-rbc-hgb-and-hct\">कंप्लीट ब्लड काउंट (CBC)</a> में WBC होता है; कभी लैब डिफरेंशियल (न्यूट्रोफिल, लिम्फोसाइट्स, मोनोसाइट्स आदि) भी देता है। <strong>लो WBC</strong> (ल्यूकोपेनिया) का मतलब है कुल काउंट लैब के रेफरेंस रेंज से नीचे है—लेकिन कुल काउंट सिर्फ \"लो न्यूट्रोफिल्स\" जैसी चीज़ नहीं है: डिफरेंशियल बताता है कौन सा टाइप लो है और डॉक्टर को व्याख्या में मदद करता है।</p>"),
        Section(id="what-low-means", level=2, heading="लो WBC का क्या मतलब है?",
                body_html="<p>लो WBC का मतलब है रेफरेंस रेंज की तुलना में कम वाइट ब्लड सेल। इसकी वजह बोन मैरो द्वारा कम सेल बनना, सेल का ज़्यादा इस्तेमाल या टूटना, या दोनों हो सकते हैं। यह एक <em>फाइंडिंग</em> है, निदान नहीं: कई कारण संदर्भ में अस्थायी या हानिरहित होते हैं; कुछ में फॉलो-अप चाहिए। डॉक्टर WBC डिफरेंशियल (जैसे लो न्यूट्रोफिल्स बनाम लो लिम्फोसाइट्स), लक्षण और बाकी रिज़ल्ट देखेंगे।</p>"),
        Section(id="common-causes", level=2, heading="लो WBC के आम कारण",
                body_html="<p>आम कारण: <strong>कुछ दवाएं</strong> (कीमो, इम्यूनोसप्रेसेंट्स या बोन मैरो पर असर डालने वाली); <strong>वायरल इन्फेक्शन</strong> (फ्लू, COVID-19 आदि) जो काउंट अस्थायी रूप से कम कर सकते हैं; बीमारी या इलाज से <strong>बोन मैरो सप्रेशन</strong>; <strong>न्यूट्रिशनल कमी</strong> (B12, फोलेट); <strong>ऑटोइम्यून या इन्फ्लेमेटरी कंडीशन</strong>; कभी <strong>स्प्लीन</strong> या दूसरे फैक्टर। हर लो WBC गंभीर नहीं होता—संदर्भ मायने रखता है।</p>"),
        Section(id="temporary", level=2, heading="लो WBC कब अस्थायी हो सकता है?",
                body_html="<p>वायरल इन्फेक्शन के बाद, कुछ इलाज के दौरान या बाद में, या बोन मैरो पर स्ट्रेस होने पर WBC अस्थायी रूप से नीचे जा सकता है। ऐसे मामलों में कुछ हफ्ते बाद दोबारा टेस्ट अक्सर रेंज में वापस दिखाता है। डॉक्टर बताएंगे कि दोबारा करवाना है या नहीं और कब। एक ही लो रिज़ल्ट से सबसे बुरा मत मान लें।</p>"),
        Section(id="drugs-infections-immune", level=2, heading="दवाएं, इन्फेक्शन, इम्यून सिस्टम और पोषण",
                body_html="<p><strong>दवाएं:</strong> कुछ WBC कम कर सकती हैं; डॉक्टर लिस्ट देखेंगे और ज़रूरत हो तो एडजस्ट या मॉनिटर कर सकते हैं। <strong>इन्फेक्शन:</strong> वायरल इन्फेक्शन अक्सर वाइट सेल (या एक टाइप जैसे न्यूट्रोफिल्स) को अस्थायी रूप से कम करते हैं; बैक्टीरियल या दूसरे भी समय के हिसाब से असर कर सकते हैं। <strong>इम्यून या इन्फ्लेमेटरी कंडीशन</strong> सेल उत्पादन या जीवनकाल पर असर डाल सकती हैं। <strong>पोषण:</strong> B12, फोलेट या कॉपर की गंभीर कमी उत्पादन पर असर डाल सकती है। इनमें से कुछ भी अकेले \"कमज़ोर इम्यूनिटी\" नहीं दिखाता—डॉक्टर संदर्भ में व्याख्या करेंगे। रिपोर्ट साफ देखने के लिए विजिट से पहले <a href=\"/analyze\">Norya पर अपलोड</a> कर सकते हैं।</p>"),
        Section(id="result-alone", level=2, heading="क्या रिज़ल्ट अकेले काफी है?",
                body_html="<p>नहीं। एक लो WBC कारण या गंभीरता नहीं बताता। डॉक्टर इसे <strong>WBC डिफरेंशियल</strong> (<a href=\"/hi/blog/lymphocytes-high-or-low\">लिम्फोसाइट्स</a>, <a href=\"/hi/blog/monocytes-high-meaning\">मोनोसाइट्स</a> आदि), दूसरे काउंट (<a href=\"/hi/blog/what-do-low-or-high-platelets-mean\">प्लेटलेट्स</a>, रेड सेल, हीमोग्लोबिन), लक्षण और इतिहास के साथ मिलाकर देखेंगे। लैब रिज़ल्ट तस्वीर का एक हिस्सा हैं—क्लिनिकल असेसमेंट ज़रूरी है।</p>"),
        Section(id="other-params", level=2, heading="डॉक्टर आम तौर पर और कौन से पैरामीटर देखते हैं?",
                body_html="<p>अक्सर <strong>WBC डिफरेंशियल</strong> (कौन सा सेल टाइप लो है), <strong>रेड ब्लड सेल और हीमोग्लोबिन</strong>, <strong>प्लेटलेट्स</strong> और कभी <strong>B12</strong>, <strong>फोलेट</strong> या स्थिति के हिसाब से दूसरे टेस्ट देखे जाते हैं। काउंट ठीक हो रहा है या नहीं देखने के लिए बाद में WBC दोबारा करवाने को कहा जा सकता है। मकसद नंबरों को आपकी स्थिति से मिलाना है।</p>"),
        Section(id="when-to-see-doctor", level=2, heading="कब मेडिकल असेसमेंट ज़रूरी है?",
                body_html="<p>कोई भी लगातार या बिना स्पष्ट कारण लो WBC डॉक्टर से चर्चा करनी चाहिए। बुखार, बार-बार इन्फेक्शन, बिना वजह थकान, मुंह के छाले या आसानी से चोट/खून आने पर—या रिपोर्ट में बहुत लो काउंट या दूसरी अबनॉर्मलिटी हो तो—जल्दी चेकअप करवाएं। लक्षण न भी हों तो अबनॉर्मल रिज़ल्ट डॉक्टर को दिखाना और ज़रूरत हो तो फॉलो-अप करवाना सही कदम है।</p>"),
        Section(id="how-norya-helps", level=2, heading="Norya यह रिज़ल्ट कैसे आसान बनाता है",
                body_html="<p>Norya निदान नहीं करता—आपको तैयारी में मदद करता है। आप <a href=\"/analyze\">अपनी लैब रिपोर्ट अपलोड</a> कर सकते हैं और WBC व डिफरेंशियल समेत साफ सार पा सकते हैं। इससे रिज़ल्ट बेहतर समझ आता है और अपॉइंटमेंट पर सही सवाल पूछ सकते हैं। ऑप्शन और कीमत के लिए <a href=\"/pricing\">प्राइसिंग पेज</a> देखें।</p>"),
        Section(id="cta", level=2, heading="अगला कदम",
                body_html="<p>अगर आप अपने ब्लड टेस्ट—WBC और बाकी CBC—को और साफ समझना चाहते हैं तो Norya से <a href=\"/analyze\">विश्लेषण शुरू</a> कर सकते हैं। इसे डॉक्टर विजिट की तैयारी के लिए इस्तेमाल करें, मेडिकल सलाह की जगह नहीं।</p>"),
        Section(id="disclaimer", level=2, heading="अस्वीकरण",
                body_html="<p><strong>यह सामग्री केवल जानकारी के लिए है और मेडिकल सलाह या निदान की जगह नहीं लेती।</strong> लो WBC के कई कारण हो सकते हैं; केवल वही स्वास्थ्यकर्मी जो आपकी हिस्ट्री और संदर्भ जानता है, रिज़ल्ट की सही व्याख्या कर सकता है। हमेशा लैब रिज़ल्ट डॉक्टर से चर्चा करें।</p>"),
    ]


def _sections_ar() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="انخفاض كريات الدم البيضاء: الأسباب الشائعة",
                body_html="<p>انخفاض عدد كريات الدم البيضاء (WBC) في التقرير المخبري قد يثير القلق، لكنه لا يعني دائماً شيئاً خطيراً. فهم ما يقيسه WBC وما الذي يسبب غالباً انخفاضاً يساعدك على التحضير لحوار هادئ مع الطبيب. هذا الدليل يشرح انخفاض WBC بلغة بسيطة—بدون إثارة ذعر—ويوجهك للخطوات التالية المناسبة.</p>"),
        Section(id="what-is-wbc", level=2, heading="ما هو WBC وماذا يُقاس؟",
                body_html="<p><strong>WBC</strong> (كريات الدم البيضاء أو الكريات البيض) هو العدد الكلي لكرات الدم البيضاء في حجم معين من الدم. تساعد في مكافحة العدوى والاستجابة للالتهاب. تحليل <a href=\"/ar/blog/how-to-understand-wbc-rbc-hgb-and-hct\">عدّ الدم الكامل</a> يتضمن WBC؛ أحياناً يعطي المختبر تفريق الكريات (العدلات، اللمفاويات، الوحيدات، إلخ). <strong>انخفاض WBC</strong> (قلة الكريات البيض) يعني أن المجموع دون نطاق المرجع—لكن المجموع ليس مطابقاً لـ\"العدلات المنخفضة\" وحدها: التفريق يوضح أي نوع منخفض ويساعد الطبيب على التفسير.</p>"),
        Section(id="what-low-means", level=2, heading="ماذا يعني انخفاض WBC؟",
                body_html="<p>انخفاض WBC يعني وجود كريات بيضاء أقل من نطاق المرجع. الأسباب قد تكون نقص إنتاج من نخاع العظم، أو استهلاك/تدمير أسرع للخلايا، أو كليهما. إنه <em>نتيجة</em> وليس تشخيصاً: أسباب كثيرة مؤقتة أو غير ذات شأن في السياق؛ وأخرى تحتاج متابعة. الطبيب ينظر إلى تفريق الكريات (مثلاً العدلات مقابل اللمفاويات المنخفضة) والأعراض وباقي النتائج.</p>"),
        Section(id="common-causes", level=2, heading="أسباب شائعة لانخفاض WBC",
                body_html="<p>أسباب نموذجية: <strong>أدوية معينة</strong> (كيمياء، مثبطات مناعة أو أخرى تؤثر على نخاع العظم)؛ <strong>عدوى فيروسية</strong> (إنفلونزا، COVID-19، إلخ) تخفض العدد مؤقتاً؛ <strong>كبت نخاع العظم</strong> بسبب مرض أو علاج؛ <strong>نقص تغذوي</strong> (B12، فولات)؛ <strong>أمراض مناعة ذاتية أو التهابية</strong>؛ أحياناً عوامل <strong>طحالية</strong> أو غيرها. ليس كل انخفاض WBC خطيراً—السياق مهم.</p>"),
        Section(id="temporary", level=2, heading="متى يمكن أن يكون انخفاض WBC مؤقتاً؟",
                body_html="<p>قد ينخفض WBC مؤقتاً بعد عدوى فيروسية، أثناء أو بعد بعض العلاجات، أو تحت ضغط على نخاع العظم. في مثل هذه الحالات تكرار الفحص بعد أسابيع غالباً يظهر عودة العدد للنطاق. الطبيب يحدد إن كان التكرار ضرورياً ومتى. تجنب استنتاج الأسوأ من نتيجة منخفضة واحدة.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="الأدوية والعدوى والمناعة والتغذية",
                body_html="<p><strong>الأدوية:</strong> بعضها قد يخفض WBC؛ الطبيب يراجع القائمة وقد يعدّل أو يراقب. <strong>العدوى:</strong> الفيروسية غالباً تخفض الكريات البيضاء (أو نوعاً واحداً مثل العدلات) مؤقتاً؛ البكتيرية أو غيرها قد تؤثر حسب التوقيت. <strong>أمراض مناعية أو التهابية</strong> قد تؤثر على الإنتاج أو بقاء الخلايا. <strong>التغذية:</strong> نقص شديد في B12 أو الفولات أو النحاس قد يؤثر على الإنتاج. لا شيء من ذلك يعني بمفرده \"جهاز مناعة ضعيف\"—الطبيب يفسر في السياق. للحصول على صورة أوضح لتقريرك يمكنك <a href=\"/analyze\">رفعه إلى Norya</a> للحصول على ملخص بلغة بسيطة قبل الموعد.</p>"),
        Section(id="result-alone", level=2, heading="هل النتيجة وحدها كافية؟",
                body_html="<p>لا. انخفاض WBC منفرد لا يحدد السبب ولا الخطورة. الطبيب يجمعه مع <strong>تفريق الكريات</strong> (<a href=\"/ar/blog/lymphocytes-high-or-low\">اللمفاويات</a>, <a href=\"/ar/blog/monocytes-high-meaning\">الوحيدات</a>، إلخ)، أعداد أخرى (<a href=\"/ar/blog/what-do-low-or-high-platelets-mean\">الصفيحات</a>، كريات حمراء، هيموغلوبين)، الأعراض والتاريخ. نتائج المختبر جزء من الصورة—التقييم السريري أساسي.</p>"),
        Section(id="other-params", level=2, heading="أي معايير أخرى يفحصها الطبيب عادة؟",
                body_html="<p>غالباً يراجع <strong>تفريق الكريات</strong> (أي نوع منخفض)، <strong>كريات الدم الحمراء والهيموغلوبين</strong>، <strong>الصفيحات</strong> وأحياناً <strong>B12</strong>، <strong>الفولات</strong> أو فحوص أخرى حسب الحالة. قد يُقترح تكرار WBC لاحقاً لمعرفة إن كان العدد يعود. الهدف مطابقة الأرقام مع وضعك الصحي.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="متى تحتاج تقييماً طبياً؟",
                body_html="<p>أي انخفاض WBC مستمر أو غير مفسر يجب مناقشته مع الطبيب. اطلب تقييماً عاجلاً إن كان لديك حمى أو عدوى متكررة أو تعب غير مفسر أو تقرحات فم أو ميل للنزف/الكدمات—أو إن التقرير يظهر عدداً منخفضاً جداً أو شذوذات أخرى. حتى دون أعراض، مشاركة نتيجة شاذة مع الطبيب خطوة صحيحة لتفسيرها واقتراح متابعة إن لزم.</p>"),
        Section(id="how-norya-helps", level=2, heading="كيف تجعل Norya هذه النتيجة أوضح",
                body_html="<p>Norya لا تضع التشخيص—نساعدك على التحضير. يمكنك <a href=\"/analyze\">رفع تقرير المختبر</a> والحصول على ملخص واضح يشرح قيمك (بما فيها WBC والتفريق) بلغة بسيطة. هكذا تفهم نتيجتك أفضل وتطرح أسئلة دقيقة في الموعد. للخيارات والأسعار: <a href=\"/pricing\">صفحة الأسعار</a>.</p>"),
        Section(id="cta", level=2, heading="الخطوة التالية",
                body_html="<p>إن أردت تفسيراً أوضح لتحليل دمك—بما فيه WBC وباقي عدّ الدم—يمكنك <a href=\"/analyze\">بدء تحليل</a> مع Norya. استخدمه للتحضير للموعد، وليس بديلاً عن الاستشارة الطبية.</p>"),
        Section(id="disclaimer", level=2, heading="إخلاء المسؤولية",
                body_html="<p><strong>هذا المحتوى لأغراض إعلامية فقط ولا يغني عن الاستشارة أو التشخيص الطبي.</strong> انخفاض WBC قد يكون له أسباب كثيرة؛ فقط من يعرف سياقك يمكنه تفسيره. ناقش دائماً نتائج المختبر مع الطبيب.</p>"),
    ]


def get_low_wbc_sections_by_lang():
    return {
        "tr": _sections_tr(),
        "en": _sections_en(),
        "es": _sections_es(),
        "de": _sections_de(),
        "fr": _sections_fr(),
        "it": _sections_it(),
        "he": _sections_he(),
        "hi": _sections_hi(),
        "ar": _sections_ar(),
    }


def get_low_wbc_faq_schema_qa():
    return {
        "en": [
            {"question": "Is low WBC serious?", "answer": "Not always. A low WBC can be temporary (e.g. after a viral infection or certain medications) or due to conditions that need monitoring. Only your doctor, with your full history and other tests, can say how significant it is for you."},
            {"question": "Can low WBC be temporary?", "answer": "Yes. Viral infections, some drugs, or stress on the bone marrow can cause a temporary drop. A repeat test is often used to see if the count returns to the reference range."},
            {"question": "What infections can affect WBC?", "answer": "Many viral infections (e.g. flu, COVID-19) can temporarily lower WBC or one type (e.g. neutrophils). Some bacterial or other infections can also affect counts depending on timing. Your doctor interprets this with your symptoms and the WBC differential."},
            {"question": "Does low WBC always mean a weak immune system?", "answer": "No. A low total WBC is a lab finding with many possible causes. It does not automatically mean your immune system is weak; context, the differential, and your clinical picture matter. Your doctor can explain what it means for you."},
            {"question": "What other blood test markers should be checked?", "answer": "Doctors often look at the WBC differential (neutrophils, lymphocytes, monocytes, etc.), red blood cells, haemoglobin, platelets, and sometimes B12, folate, or other tests—depending on your situation and symptoms."},
        ],
        "tr": [
            {"question": "Düşük WBC ciddi mi?", "answer": "Her zaman değil. Düşük WBC geçici olabilir (ör. viral enfeksiyon veya bazı ilaçlar sonrası) veya takip gerektiren durumlara bağlı olabilir. Sadece hekiminiz, öykünüz ve diğer testlerle birlikte sizin için ne kadar anlamlı olduğunu söyleyebilir."},
            {"question": "Düşük WBC geçici olabilir mi?", "answer": "Evet. Viral enfeksiyonlar, bazı ilaçlar veya kemik iliği üzerindeki stres geçici bir düşüşe neden olabilir. Sayının referans aralığına dönüp dönmediğini görmek için sıklıkla tekrar test yapılır."},
            {"question": "Hangi enfeksiyonlar WBC'yi etkiler?", "answer": "Birçok viral enfeksiyon (grip, COVID-19 vb.) WBC'yi veya bir türü (örn. nötrofilleri) geçici olarak düşürebilir. Bazı bakteriyel veya diğer enfeksiyonlar da zamana bağlı olarak sayıyı etkileyebilir. Hekiminiz bunu belirtileriniz ve lökosit formülüyle yorumlar."},
            {"question": "Düşük WBC her zaman zayıf bağışıklık mı demek?", "answer": "Hayır. Düşük toplam WBC birçok olası nedeni olan bir laboratuvar bulgusudur. Bağışıklık sisteminizin zayıf olduğu anlamına gelmez; bağlam, formül ve klinik tablonuz önemlidir. Hekiminiz sizin için ne anlama geldiğini açıklayabilir."},
            {"question": "Başka hangi kan değerleri kontrol edilmeli?", "answer": "Hekimler sıklıkla lökosit formülünü (nötrofil, lenfosit, monosit vb.), kırmızı küreleri, hemoglobini, trombositleri ve bazen B12, folat veya diğer testleri—durumunuza ve belirtilerinize göre—değerlendirir."},
        ],
        "es": [
            {"question": "¿Es grave tener el WBC bajo?", "answer": "No siempre. Un WBC bajo puede ser temporal (p. ej. tras una infección viral o ciertos medicamentos) o deberse a situaciones que requieren seguimiento. Solo tu médico, con tu historia completa y otras pruebas, puede decirte qué importancia tiene para ti."},
            {"question": "¿Puede el WBC bajo ser temporal?", "answer": "Sí. Infecciones virales, algunos fármacos o estrés sobre la médula ósea pueden provocar una bajada temporal. A menudo se repite el análisis para ver si el recuento vuelve al rango de referencia."},
            {"question": "¿Qué infecciones pueden afectar al WBC?", "answer": "Muchas infecciones virales (p. ej. gripe, COVID-19) pueden bajar temporalmente el WBC o un tipo (p. ej. neutrófilos). Algunas bacterianas u otras también pueden afectar los recuentos según el momento. Tu médico lo interpreta con tus síntomas y la fórmula leucocitaria."},
            {"question": "¿WBC bajo significa siempre sistema inmune débil?", "answer": "No. Un WBC total bajo es un hallazgo analítico con muchas causas posibles. No implica automáticamente que tu sistema inmune sea débil; el contexto, la fórmula y tu cuadro clínico importan. Tu médico puede explicarte qué significa para ti."},
            {"question": "¿Qué otros marcadores de sangre hay que revisar?", "answer": "Los médicos suelen revisar la fórmula leucocitaria (neutrófilos, linfocitos, monocitos, etc.), glóbulos rojos, hemoglobina, plaquetas y a veces B12, folato u otras pruebas, según tu situación y síntomas."},
        ],
        "de": [
            {"question": "Ist niedriges WBC ernst?", "answer": "Nicht immer. Ein niedriges WBC kann vorübergehend sein (z. B. nach Virusinfekt oder bestimmten Medikamenten) oder auf Zustände zurückgehen, die Kontrolle brauchen. Nur Ihr Arzt kann mit Ihrer Anamnese und weiteren Befunden einschätzen, wie bedeutsam es für Sie ist."},
            {"question": "Kann niedriges WBC vorübergehend sein?", "answer": "Ja. Virusinfektionen, manche Medikamente oder Belastung des Knochenmarks können einen vorübergehenden Abfall verursachen. Oft wird die Bestimmung wiederholt, um zu prüfen, ob der Wert in den Referenzbereich zurückkehrt."},
            {"question": "Welche Infektionen können das WBC beeinflussen?", "answer": "Viele Virusinfektionen (z. B. Grippe, COVID-19) können WBC oder einen Typ (z. B. Neutrophile) vorübergehend senken. Auch bakterielle oder andere Infektionen können je nach Zeitpunkt die Werte beeinflussen. Ihr Arzt wertet das mit Ihren Symptomen und dem Differentialblutbild aus."},
            {"question": "Bedeutet niedriges WBC immer schwaches Immunsystem?", "answer": "Nein. Ein niedriges Gesamt-WBC ist ein Laborbefund mit vielen möglichen Ursachen. Es bedeutet nicht automatisch ein schwaches Immunsystem; Kontext, Differential und Ihr klinisches Bild zählen. Ihr Arzt kann erklären, was es für Sie bedeutet."},
            {"question": "Welche anderen Blutwerte sollten geprüft werden?", "answer": "Ärzte prüfen oft das Differentialblutbild (Neutrophile, Lymphozyten, Monozyten usw.), Erythrozyten, Hämoglobin, Thrombozyten und manchmal B12, Folsäure oder weitere Tests—je nach Situation und Symptomen."},
        ],
        "fr": [
            {"question": "Un WBC bas est-il grave ?", "answer": "Pas toujours. Un WBC bas peut être temporaire (p. ex. après une infection virale ou certains médicaments) ou lié à des situations nécessitant un suivi. Seul votre médecin, avec votre histoire complète et d'autres examens, peut dire ce que cela signifie pour vous."},
            {"question": "Le WBC bas peut-il être temporaire ?", "answer": "Oui. Les infections virales, certains médicaments ou une pression sur la moelle osseuse peuvent provoquer une baisse temporaire. Un nouveau prélèvement est souvent fait pour voir si le taux revient dans la fourchette de référence."},
            {"question": "Quelles infections peuvent affecter le WBC ?", "answer": "Beaucoup d'infections virales (grippe, COVID-19, etc.) peuvent faire baisser temporairement le WBC ou un type (p. ex. neutrophiles). Certaines infections bactériennes ou autres peuvent aussi influencer les chiffres selon le moment. Votre médecin interprète cela avec vos symptômes et la formule leucocytaire."},
            {"question": "WBC bas signifie-t-il toujours un système immunitaire faible ?", "answer": "Non. Un WBC total bas est un résultat de laboratoire avec de nombreuses causes possibles. Cela ne signifie pas automatiquement un système immunitaire faible ; le contexte, la formule et votre tableau clinique comptent. Votre médecin peut vous expliquer ce que cela signifie pour vous."},
            {"question": "Quels autres marqueurs sanguins faut-il vérifier ?", "answer": "Les médecins regardent souvent la formule leucocytaire (neutrophiles, lymphocytes, monocytes, etc.), les globules rouges, l'hémoglobine, les plaquettes et parfois B12, folates ou d'autres examens—selon votre situation et vos symptômes."},
        ],
        "it": [
            {"question": "Un WBC basso è grave?", "answer": "Non sempre. Un WBC basso può essere temporaneo (es. dopo un'infezione virale o certi farmaci) o legato a condizioni che richiedono monitoraggio. Solo il tuo medico, con la tua storia e altri esami, può dirti quanto è significativo per te."},
            {"question": "Il WBC basso può essere temporaneo?", "answer": "Sì. Infezioni virali, alcuni farmaci o stress sul midollo osseo possono causare un calo temporaneo. Spesso si ripete l'esame per vedere se il valore torna nell'intervallo di riferimento."},
            {"question": "Quali infezioni possono influenzare il WBC?", "answer": "Molte infezioni virali (es. influenza, COVID-19) possono abbassare temporaneamente il WBC o un tipo (es. neutrofili). Anche alcune batteriche o altre possono influire sui valori a seconda del momento. Il medico lo interpreta con i sintomi e la formula leucocitaria."},
            {"question": "WBC basso significa sempre sistema immunitario debole?", "answer": "No. Un WBC totale basso è un reperto di laboratorio con molte cause possibili. Non significa automaticamente sistema immunitario debole; contano il contesto, la formula e il quadro clinico. Il medico può spiegarti cosa significa per te."},
            {"question": "Quali altri marcatori del sangue vanno controllati?", "answer": "I medici controllano spesso la formula leucocitaria (neutrofili, linfociti, monociti, ecc.), globuli rossi, emoglobina, piastrine e a volte B12, folati o altri esami—a seconda della situazione e dei sintomi."},
        ],
        "he": [
            {"question": "האם WBC נמוך חמור?", "answer": "לא תמיד. WBC נמוך יכול להיות זמני (למשל אחרי זיהום נגיפי או תרופות מסוימות) או קשור למצבים שדורשים מעקב. רק הרופא שלך, עם ההיסטוריה והבדיקות האחרות, יכול לומר עד כמה זה משמעותי עבורך."},
            {"question": "האם WBC נמוך יכול להיות זמני?", "answer": "כן. זיהומים נגיפיים, תרופות מסוימות או עומס על מח העצם יכולים לגרום לירידה זמנית. לעיתים חוזרים על הבדיקה כדי לראות אם הערך חוזר לטווח הייחוס."},
            {"question": "אילו זיהומים יכולים להשפיע על WBC?", "answer": "זיהומים נגיפיים רבים (למשל שפעת, COVID-19) יכולים להוריד זמנית את ה-WBC או סוג אחד (למשל נויטרופילים). גם זיהומים חיידקיים או אחרים יכולים להשפיע על הספירות בהתאם למועד. הרופא יפרש זאת עם התסמינים והנוסחה."},
            {"question": "האם WBC נמוך תמיד מעיד על מערכת חיסון חלשה?", "answer": "לא. WBC נמוך בסך הכול הוא ממצא מעבדתי עם סיבות רבות אפשריות. זה לא אומר אוטומטית שמערכת החיסון חלשה; ההקשר, הנוסחה והתמונה הקלינית חשובים. הרופא יכול להסביר מה זה אומר עבורך."},
            {"question": "אילו סמנים נוספים בדם צריך לבדוק?", "answer": "רופאים בודקים לעיתים את הנוסחה (נויטרופילים, לימפוציטים, מונוציטים וכו'), כדוריות אדומות, המוגלובין, טסיות ולעיתים B12, חומצה פולית או בדיקות אחרות—לפי המצב והתסמינים."},
        ],
        "hi": [
            {"question": "क्या लो WBC गंभीर है?", "answer": "हमेशा नहीं। लो WBC अस्थायी हो सकता है (जैसे वायरल इन्फेक्शन या कुछ दवाओं के बाद) या ऐसी स्थितियों की वजह से जिन पर नज़र रखनी पड़ती है। सिर्फ आपका डॉक्टर, पूरी हिस्ट्री और दूसरे टेस्ट के साथ बता सकता है कि आपके लिए इसका क्या मतलब है।"},
            {"question": "क्या लो WBC अस्थायी हो सकता है?", "answer": "हाँ। वायरल इन्फेक्शन, कुछ दवाएँ या बोन मैरो पर दबाव अस्थायी गिरावट पैदा कर सकते हैं। अक्सर यह देखने के लिए टेस्ट दोहराया जाता है कि काउंट रेफरेंस रेंज में वापस आता है या नहीं।"},
            {"question": "कौन से इन्फेक्शन WBC को प्रभावित कर सकते हैं?", "answer": "कई वायरल इन्फेक्शन (जैसे फ्लू, COVID-19) WBC या एक प्रकार (जैसे न्यूट्रोफिल) को अस्थायी रूप से कम कर सकते हैं। कुछ बैक्टीरियल या अन्य इन्फेक्शन भी समय के हिसाब से काउंट प्रभावित कर सकते हैं। डॉक्टर इसे आपके लक्षणों और WBC डिफरेंशियल के साथ समझाते हैं।"},
            {"question": "क्या लो WBC का मतलब हमेशा कमजोर इम्यून सिस्टम है?", "answer": "नहीं। लो टोटल WBC एक लैब फाइंडिंग है जिसके कई कारण हो सकते हैं। इसका मतलब यह नहीं कि इम्यून सिस्टम कमजोर है; कॉन्टेक्स्ट, डिफरेंशियल और क्लिनिकल पिक्चर मायने रखते हैं। डॉक्टर बता सकते हैं कि आपके लिए क्या मतलब है।"},
            {"question": "और कौन से ब्लड मार्कर चेक करवाने चाहिए?", "answer": "डॉक्टर अक्सर WBC डिफरेंशियल (न्यूट्रोफिल, लिम्फोसाइट्स, मोनोसाइट्स आदि), रेड ब्लड सेल्स, हीमोग्लोबिन, प्लेटलेट्स और कभी-कभी B12, फोलेट या दूसरे टेस्ट देखते हैं—स्थिति और लक्षणों के हिसाब से।"},
        ],
        "ar": [
            {"question": "هل انخفاض WBC خطير؟", "answer": "ليس دائماً. انخفاض WBC قد يكون مؤقتاً (مثلاً بعد عدوى فيروسية أو أدوية معينة) أو مرتبطاً بحالات تحتاج متابعة. الطبيب فقط، مع تاريخك الكامل والتحاليل الأخرى، يستطيع أن يحدد مدى أهميته لك."},
            {"question": "هل يمكن أن يكون انخفاض WBC مؤقتاً؟", "answer": "نعم. العدوى الفيروسية أو بعض الأدوية أو الضغط على نخاع العظم قد تسبب انخفاضاً مؤقتاً. غالباً يُعاد التحليل لمعرفة إن عاد العدد إلى نطاق المرجع."},
            {"question": "ما العدوى التي تؤثر على WBC؟", "answer": "كثير من العدوى الفيروسية (مثل الإنفلونزا، كوفيد-19) قد تخفض WBC أو نوعاً واحداً (مثل العدلات) مؤقتاً. بعض البكتيرية أو غيرها قد تؤثر على الأعداد حسب التوقيت. الطبيب يفسر ذلك مع الأعراض وصيغة الكريات البيضاء."},
            {"question": "هل انخفاض WBC يعني دائماً جهاز مناعة ضعيف؟", "answer": "لا. انخفاض إجمالي WBC هو نتيجة تحليل لها أسباب كثيرة محتملة. لا يعني تلقائياً ضعف الجهاز المناعي؛ السياق والصيغة واللوحة السريرية مهمة. الطبيب يشرح ما يعنيه ذلك لك."},
            {"question": "ما المؤشرات الدموية الأخرى التي يجب فحصها؟", "answer": "الأطباء ينظرون غالباً إلى صيغة الكريات البيضاء (العدلات، اللمفاويات، الوحيدات، إلخ)، الكريات الحمراء، الهيموغلوبين، الصفيحات وأحياناً B12، الفولات أو تحاليل أخرى—حسب وضعك والأعراض."},
        ],
    }


def _sections_tr() -> list:
    from app.blog_i18n import Section
    return [
        Section(id="intro", level=2, heading="Düşük WBC: yaygın nedenler",
                body_html="<p>Laboratuvar raporunuzda beyaz küre (WBC) sayısının düşük çıkması endişe uyandırabilir; ancak her zaman ciddi bir şey anlamına gelmez. WBC&rsquo;nin ne ölçtüğünü ve düşük sonucun yaygın nedenlerini bilmek, hekiminizle sakin bir görüşme için hazırlanmanıza yardım eder. Bu rehber, düşük WBC&rsquo;yi panik yaratmadan sade bir dille açıklar ve doğru adımlara yönlendirir.</p>"),
        Section(id="what-is-wbc", level=2, heading="WBC nedir, neyi ölçer?",
                body_html="<p><strong>WBC</strong> (beyaz kan hücreleri, lökosit) belirli bir kan hacmindeki beyaz kan hücrelerinin toplam sayısıdır. Bu hücreler enfeksiyonlarla savaşmaya ve iltihaba yanıt vermeye yardım eder. Rutin <a href=\"/tr/blog/wbc-rbc-hgb-hct-nasil-okunur\">tam kan sayımında (CBC)</a> WBC yer alır; laboratuvar &ldquo;lökosit formülü&rdquo; (nötrofil, lenfosit, monosit vb.) da verebilir. <strong>Düşük WBC</strong> (lökopeni), toplam sayının laboratuvar referans aralığının altında olduğu anlamına gelir—ancak toplam sayı tek başına &ldquo;düşük nötrofil&rdquo; ile aynı değildir: formül hangi türün düşük olduğunu gösterir ve hekimin yorumuna yardım eder.</p>"),
        Section(id="what-low-means", level=2, heading="Düşük WBC ne demektir?",
                body_html="<p>Düşük WBC, kanınızda o laboratuvarın referans aralığına göre daha az beyaz kan hücresi olduğu anlamına gelir. Kemik iliğinin daha az hücre üretmesi, hücrelerin daha hızlı kullanılması veya yıkılması veya ikisinin birlikte olması buna neden olabilir. Bu bir <em>bulgu</em>dur, teşhis değildir: birçok neden bağlama göre geçici veya zararsızdır; bazıları ise takip gerektirir. Hekiminiz lökosit formülünü (örn. düşük nötrofil vs düşük lenfosit), belirtilerinizi ve diğer sonuçları birlikte değerlendirir.</p>"),
        Section(id="common-causes", level=2, heading="Düşük WBC'nin yaygın nedenleri",
                body_html="<p>Yaygın nedenler: <strong>bazı ilaçlar</strong> (kemoterapi, immünsupresanlar veya kemik iliğini etkileyebilen ilaçlar); <strong>viral enfeksiyonlar</strong> (grip, COVID-19 vb. sayıyı geçici düşürebilir); hastalık veya tedaviye bağlı <strong>kemik iliği baskılanması</strong>; kan hücresi yapımını etkileyen <strong>beslenme eksiklikleri</strong> (B12, folat); <strong>otoimmün veya iltihabi durumlar</strong>; bazen <strong>dalak</strong> veya diğer faktörler. Düşük WBC&rsquo;si olan herkeste ciddi bir durum yoktur—bağlam önemlidir.</p>"),
        Section(id="temporary", level=2, heading="Geçici düşük WBC görülebilen durumlar",
                body_html="<p>Viral enfeksiyon sonrası, bazı tedaviler sırasında veya hemen sonrasında, ya da kemik iliği stresinde WBC geçici olarak düşebilir. Böyle durumlarda birkaç hafta sonra tekrarlanan testte sayı sıklıkla normale döner. Tekrara gerek olup olmadığını ve ne zaman yapılacağını hekiminiz söyler. Tek bir düşük sonuçtan en kötüyü varsaymaktan kaçının.</p>"),
        Section(id="drugs-infections-immune", level=2, heading="İlaçlar, enfeksiyonlar, bağışıklık ve beslenme",
                body_html="<p><strong>İlaçlar:</strong> Bazı ilaçlar WBC&rsquo;yi düşürebilir; hekiminiz listeyi gözden geçirip gerekirse ilacı veya takibi ayarlar. <strong>Enfeksiyonlar:</strong> Viral enfeksiyonlar sıklıkla beyaz hücrelerde (veya bir türde, örn. nötrofillerde) geçici düşüşe neden olur; bakteriyel veya diğer enfeksiyonlar da zamana bağlı etkileyebilir. <strong>Bağışıklık veya iltihabi durumlar</strong> üretimi veya hücre yaşam süresini etkileyebilir. <strong>Beslenme:</strong> B12, folat veya bakır eksikliği kan hücresi yapımını etkileyebilir. Bunlar basit anlamda bağışıklığınızın &ldquo;zayıf&rdquo; olduğu anlamına gelmez—hekiminiz bağlamında yorumlar. Raporunuzu daha net görmek için randevudan önce <a href=\"/analyze\">Norya&rsquo;ya yükleyerek</a> sade dilde özet alabilirsiniz.</p>"),
        Section(id="result-alone", level=2, heading="Sonuç tek başına yeterli mi?",
                body_html="<p>Hayır. Tek bir düşük WBC nedeni veya ciddiyeti göstermez. Hekiminiz bunu <strong>lökosit formülü</strong> (<a href=\"/tr/blog/lymphocytes-high-or-low\">lenfosit</a>, <a href=\"/tr/blog/monocytes-high-meaning\">monosit</a> vb.), diğer kan sayımları (<a href=\"/tr/blog/trombosit-yuksekligi-ve-dusuklugu-ne-demek\">trombosit</a>, kırmızı küre, hemoglobin), belirtileriniz ve öykünüzle birlikte değerlendirir. Laboratuvar sonuçları tablonun bir parçasıdır—klinik değerlendirme şarttır.</p>"),
        Section(id="other-params", level=2, heading="Hekimler genelde hangi ek parametrelere bakar?",
                body_html="<p>Sıklıkla <strong>lökosit formülünü</strong> (hangi hücre türü düşük), <strong>kırmızı küre ve hemoglobin</strong>, <strong>trombosit</strong> ve bazen <strong>B12</strong>, <strong>folat</strong> veya duruma göre diğer testleri inceler. Sayının düzelip düzelmediğini görmek için bir süre sonra WBC tekrarı istenebilir. Amaç sayıları sağlık öykünüzle eşleştirmektir.</p>"),
        Section(id="when-to-see-doctor", level=2, heading="Ne zaman tıbbi değerlendirme gerekir?",
                body_html="<p>Kalıcı veya açıklanamayan düşük WBC mutlaka hekimle görüşülmelidir. Ateş, tekrarlayan enfeksiyonlar, açıklanamayan yorgunluk, ağız yaraları veya kolay morarma/kanama varsa—veya raporunuzda çok düşük sayı veya diğer anormallikler varsa—zaman kaybetmeden değerlendirme yaptırın. Belirti olmasa bile anormal sonucu hekiminizle paylaşmak ve gerekirse takip önermesini istemek doğru adımdır.</p>"),
        Section(id="how-norya-helps", level=2, heading="Norya bu sonucu nasıl anlaşılır kılar?",
                body_html="<p>Norya teşhis koymaz—randevunuza hazırlanmanıza yardım eder. <a href=\"/analyze\">Laboratuvar raporunuzu yükleyerek</a> değerlerinizi (WBC ve formül dahil) sade dilde açıklayan net bir özet alabilirsiniz. Böylece sonucunuzu daha iyi anlayıp randevuda doğru soruları sorabilirsiniz. Seçenekler ve fiyatlar için <a href=\"/pricing\">fiyatlandırma sayfamıza</a> bakın.</p>"),
        Section(id="cta", level=2, heading="Sonraki adım",
                body_html="<p>Kan tahlilinizi—WBC ve diğer CBC değerleri dahil—daha net anlamak isterseniz Norya ile <a href=\"/analyze\">analiz başlatabilirsiniz</a>. Bunu hekim randevunuza hazırlık için kullanın; tıbbi tavsiyenin yerine koymayın.</p>"),
        Section(id="disclaimer", level=2, heading="Uyarı",
                body_html="<p><strong>Bu içerik yalnızca bilgilendirme amaçlıdır; tıbbi tavsiye veya teşhis yerine geçmez.</strong> Düşük WBC&rsquo;nin birçok nedeni olabilir; sonucunuzu ancak öykünüzü ve bağlamını bilen bir sağlık profesyoneli doğru yorumlayabilir. Laboratuvar sonuçlarınızı her zaman bir hekimle görüşün.</p>"),
    ]
